### ISSUE TITLE
Building a simple swing panel

### ISSUE THREAD

**Issue by meirlo** [LibreOffice/noa-libre#15]
Hi,
I'm trying to build an Swing panel which should display LibreOffice writer in it.
I tried to wrap the code with the documentation along with the officeLoader,
but couldn't make it work.
Here is the code snippets (basically a copy- paste of the documentation + OfficeLoader):
`https://gist.github.com/meirlo/89f90996369d57b8bd4c5851ecd632b0`

running the code results in the following error:

> java.lang.VerifyError: Bad type on operand stack
> Exception Details:
>   Location:
>     javax/swing/JFrame.getAccessibleContext()Ljavax/accessibility/AccessibleContext; @16: putfield
>   Reason:
>     Type 'javax/swing/JFrame$AccessibleJFrame' (current frame, stack[1]) is not assignable to 'javax/accessibility/AccessibleContext'
>   Current Frame:
>     bci: @16
>     flags: { }
>     locals: { 'javax/swing/JFrame' }
>     stack: { 'javax/swing/JFrame', 'javax/swing/JFrame$AccessibleJFrame' }
>   Bytecode:
>     0x0000000: 2ab4 0005 c700 0f2a bb00 6659 2ab7 0067
>     0x0000010: b500 052a b400 05b0  
>   Stackmap Table:
>     same_frame(@19)

Also, I tried to embed open office into my existing application and got slight different error:

> ag.ion.bion.officelayer.util.Assert$AssertionException: ag.ion.bion.officelayer.internal.desktop.Frame: The submitted com.sun.star.frame.XFrame is not valid.
>   at ag.ion.bion.officelayer.util.Assert.isNotNull(Assert.java:91)
>   at ag.ion.bion.officelayer.internal.desktop.Frame.<init>(Frame.java:255)

Any help will be appreciated :)

Thanks,
Meir

**Comment by meirlo** [comment]
The problem was that AWT can't draw unless the panel is visible.
Otherwise it will throw those weird exceptions.
