### ISSUE TITLE
nativeview.dll in 64bit Java and with 64bit LibreOffice (nativeview.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform)

### ISSUE THREAD

**Issue by phermsdorf** [LibreOffice/noa-libre#22]
Hi,

we are in the process of switching our application to 64bit. We move from a 32bit Java and LibreOffice to the 64bit versions.
I updated the Java binding (like officebean.jar and unoil.jar) with the versions from the 64bit LibreOffice installation (<LibreOffice5Installation>/program/classes) and tried using the libnativeview.so from the 64bit folder of noa-libre (is this even important when on Windows?)

The background startup of the LibreOffice process seem to work but when accessing the UI part the application is failing with:

```
configuration\org.eclipse.osgi\5\0\.cp\lib\nativeview.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at ag.ion.bion.officelayer.NativeView.loadLibrary(NativeView.java:230)
	at ag.ion.bion.officelayer.NativeView.<init>(NativeView.java:135)
	at ag.ion.bion.officelayer.internal.application.connection.LocalOfficeConnection.getOfficeFrame(LocalOfficeConnection.java:390)
	at ag.ion.bion.officelayer.internal.desktop.DesktopService.constructNewOfficeFrame(DesktopService.java:264)
	at com.godyo.noa.openoffice.panel.OfficePanel.activateNewFrame(OfficePanel.java:520)

```
So the problem seems to be that the provided version of nativeview.dll is 32bit!?

Has anybody a working embedded LibreOffice in a 64bit Java Apllication?

**Comment by anti43** [comment]
This is weird. Here they compiled a 64bit one:
https://github.com/emiliotrussardi/noa-libre/issues/4

But this issues states the last one **here** _is_ 64bit
https://github.com/LibreOffice/noa-libre/issues/17

**Comment by phermsdorf** [comment]
Thanks for the pointer! 
That version indeed works! I now have an embedded LibreOffice. Needs more testing but for now i will close this issue.

I also read the comment on #17 , but can't verify that comment.

Thanks!
